[package]
name = "jotsy"
version = "0.1.0"
edition = "2021"
authors = ["Sayan Nandan <nandansayan@outlook.com>"]

[dependencies]
axum = { version = "0.4.4", features = ["headers"] }
tokio = { version = "1.16.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.2.1", features = ["fs"] }
tower-cookies = "0.4.1"
skytable = { version = "0.7.0-alpha.4", features = [
    "aio",
], default-features = false }
